
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Z = 2;
  public static final int NUMBER = 5;
  public static final int BOOLEAN = 3;
  public static final int EOF = 0;
  public static final int STRING = 7;
  public static final int ASSIGN = 8;
  public static final int error = 1;
  public static final int IDENTIFIER = 4;
  public static final int BREAK = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Z",
  "BOOLEAN",
  "IDENTIFIER",
  "NUMBER",
  "BREAK",
  "STRING",
  "ASSIGN"
  };
}

