
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.portugol.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 15;
  public static final int SENAO = 4;
  public static final int MENOR = 16;
  public static final int ENTAO = 3;
  public static final int FP = 22;
  public static final int IGUAL = 20;
  public static final int ID = 25;
  public static final int PV = 23;
  public static final int PARA = 13;
  public static final int AP = 21;
  public static final int VIRGULA = 10;
  public static final int NUM = 26;
  public static final int FUNCAO = 8;
  public static final int MAIS = 14;
  public static final int RETORNE = 9;
  public static final int MULT = 17;
  public static final int EOF = 0;
  public static final int DIV = 18;
  public static final int TIPO_BOOL = 6;
  public static final int MAIOR = 19;
  public static final int error = 1;
  public static final int TIPO_VOID = 7;
  public static final int SE = 2;
  public static final int FACA = 11;
  public static final int ENQUANTO = 12;
  public static final int FIM = 24;
  public static final int TIPO_INT = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SE",
  "ENTAO",
  "SENAO",
  "TIPO_INT",
  "TIPO_BOOL",
  "TIPO_VOID",
  "FUNCAO",
  "RETORNE",
  "VIRGULA",
  "FACA",
  "ENQUANTO",
  "PARA",
  "MAIS",
  "MENOS",
  "MENOR",
  "MULT",
  "DIV",
  "MAIOR",
  "IGUAL",
  "AP",
  "FP",
  "PV",
  "FIM",
  "ID",
  "NUM"
  };
}

