
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 12;
  public static final int LBRACE = 2;
  public static final int COLON = 6;
  public static final int TRUE = 8;
  public static final int NULL = 10;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int FALSE = 9;
  public static final int RBRACKET = 5;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int LBRACKET = 4;
  public static final int RBRACE = 3;
  public static final int FLOAT = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "COLON",
  "COMMA",
  "TRUE",
  "FALSE",
  "NULL",
  "STRING",
  "INT",
  "FLOAT"
  };
}

