
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int UMINUS = 11;
  public static final int NUMBER = 10;
  public static final int MULT = 4;
  public static final int SEMI = 9;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int POWER = 6;
  public static final int LPAREN = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "POWER",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "NUMBER",
  "UMINUS"
  };
}

