
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ini.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMBER = 8;
  public static final int BOOLEAN = 7;
  public static final int EOF = 0;
  public static final int STRING = 6;
  public static final int RBRACK = 3;
  public static final int ID = 5;
  public static final int error = 1;
  public static final int LBRACK = 2;
  public static final int EQUALS = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACK",
  "RBRACK",
  "EQUALS",
  "ID",
  "STRING",
  "BOOLEAN",
  "NUMBER"
  };
}

